objects/Expense__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>10</precision>
        <scale>4</scale>
        <type>Currency</type>
    </fields>
    <label>Expense</label>
    <nameField>
        <displayFormat>Exp-{0000}</displayFormat>
        <label>Expense_Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Expense_Member__c.object
<CustomObject>
    <fields>
        <fullName>Contribution_Amount__c</fullName>
        <label>Contribution Amount</label>
        <precision>10</precision>
        <scale>4</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Expense_Amount__c</fullName>
        <label>Expense</label>
        <referenceTo>Expense__c</referenceTo>
        <relationshipLabel>Expense Members</relationshipLabel>
        <relationshipName>Expense_Members</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Member_Email__c</fullName>
        <label>Member Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Member__c</fullName>
        <label>Member</label>
        <referenceTo>Member__c</referenceTo>
        <relationshipLabel>Expense Members</relationshipLabel>
        <relationshipName>Expense_Member</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Expense Member</label>
    <nameField>
        <displayFormat>EM-{0000}</displayFormat>
        <label>Expense Member Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expense Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Member__c.object
<CustomObject>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Member</label>
    <nameField>
        <displayFormat>m-{0000}</displayFormat>
        <label>Member Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/EMController.cls
public class EMController
{
    public List<Expense_Member__c> expenseMembers{get;set;}
    public PageReference fetchRecord()
    {
        expenseMembers = [select Id,Name,Contribution_Amount__c,Expense_Amount__r.Amount__c,Member__r.First_Name__c,Member__r.Last_Name__c,Member_Email__c from Expense_Member__c];
        return null;
    }
    
    public PageReference Redirect()
    {
        String id= System.currentPagereference().getParameters().get('id');
        
        PageReference reRend = new PageReference('/apex/ExpenseMemberUpdate?id='+id);
        //reRend .getParameters().put('id','i.id');
        reRend.setRedirect(true);
        return reRend;
    }
    
    public PageReference toRedirect()
    {
        String id= System.currentPagereference().getParameters().get('id');
        
        PageReference reRend = new PageReference('/apex/ExpenseMemberDelete?id='+id);
        //reRend .getParameters().put('id','i.id');
        reRend.setRedirect(true);
        return reRend;
    }
}